apiVersion: v1
kind: Service
metadata:
  name: akri-video-streaming-app_1
  namespace: akri-system
  labels:
    app: akri-video-streaming-app
spec:
  selector:
    app: akri-video-streaming-app
  ports:
  - name: http
    port: 80
    targetPort: 5000
  type: LoadBalancer
